---
_target_: flwr.server.strategy.Krum
fraction_fit: 0.00001
min_fit_clients: ${num_clients_per_round_fit}
fraction_evaluate: 0.00001
min_evaluate_clients: ${num_clients_per_round_eval}
min_available_clients: ${num_clients}

on_fit_config_fn:
  _target_: server.get_on_fit_config
  config: ${config_fit}

initial_parameters:
  _target_: model.models_to_parameters
  model: ${model}