---

num_rounds: 10
num_clients: 10 
batch_size: 20
num_classes: 2
num_clients_per_round_fit: 2
num_clients_per_round_eval: 5
data_path: /home/vadi/oii/Academics/BtechProject/tutorial/data/MIMIC/mimic-iii-clinical-database-demo-1.4
config_fit: 
  lr: 0.01
  momentum: 0.9
  local_epochs: 5

defaults:
  - _self_
  - strategy: fedavg
  - model: tabular_model